### ISSUE TITLE
Theme Toggle Only Affects Home Page

### ISSUE THREAD

**Issue by Kavinesh11** [SaranDharshanSP/TN-Tourism.github.io#16]
Description:
When the dark/light theme toggle button is switched on the home page, it successfully updates the home page to the selected theme. However, navigating to any other page does not retain or apply the selected theme. The expectation is that the toggle should provide a consistent dark/light theme experience across the entire application, not just on the home page.

Steps to Reproduce:

Go to the home page and toggle the theme to dark or light.
Confirm that the home page updates correctly.
Navigate to another page in the application.
Observe that the selected theme is not retained or applied on this other page.

Expected Behavior:
The selected theme (dark or light) should persist across all pages once toggled.

Actual Behavior:
The theme only updates on the home page; other pages remain unchanged.
Proposed Solution / Ideas:

Move theme state management to a global context or higher-level component that can propagate theme changes to all pages.
Ensure that the toggle component updates a shared state or uses a theme context accessible throughout the application.

**Comment by Kavinesh11** [comment]
@SaranDharshanSP can i get assigned to it ?

**Comment by SaranDharshanSP** [comment]
> Kavinesh11

Hey @Kavinesh11  ! Noticed that you've already been assigned issues under two other repositories. Please complete those and raise PRs before requesting this issue. Excited to see your contributions!

**Comment by rev-sin** [comment]
.

**Comment by FLASH2332** [comment]
I would like to work on this issue, @SaranDharshanSP. I have experience implementing the same functionality in our Youtube-clone project. Have a look [here](https://github.com/FLASH2332/YOUTUBE).
