### ISSUE TITLE
Image Click Transition Error on Food Page

### ISSUE THREAD

**Issue by SaranDharshanSP** [SaranDharshanSP/TN-Tourism.github.io#3]
### Description
Clicking on images in the food page causes an unexpected error or glitch during the transition effect. The transition either doesn't complete properly or breaks the layout.

### Steps to Reproduce
1. Navigate to the food page.
2. Click on any image to trigger the transition effect.
3. Observe the error or unexpected behavior.

### Expected Behavior
The image should transition smoothly without any errors or layout issues.

### Current Behavior
The transition effect either breaks the layout or causes a glitch in the user interface.

### Severity
**Medium**  
*Impacts user experience but does not block functionality.*

### Suggested Fix
- Review and debug the CSS/JavaScript responsible for the transition.
- Ensure compatibility across all browsers and devices.
- Test for any conflicts with other components or scripts on the page.

**Comment by anusanth26** [comment]
Hello @SaranDharshanSP 
I am interested in working on this issue and resolving it. I will fix it without breaking the project guidelines and overall structure. Could you please assign it to me?
I am eagerly waiting for your approval...Thank You!!

**Comment by Raamprathap** [comment]
I'm interested in solving this issue @SaranDharshanSP

**Comment by SaranDharshanSP** [comment]
Hey @Raamprathap ! Under Amrita Winter of Code, only one issue can be assigned per person per repository. Please complete your currently assigned issue and raise a PR before requesting another. Looking forward to your contributions!

**Comment by SaranDharshanSP** [comment]
> Hello @SaranDharshanSP I am interested in working on this issue and resolving it. I will fix it without breaking the project guidelines and overall structure. Could you please assign it to me? I am eagerly waiting for your approval...Thank You!!

Please ask again as AMWOC started 10am today

**Comment by priyansh-narang2308** [comment]
I'm interested in solving this issue @SaranDharshanSP

**Comment by SaranDharshanSP** [comment]
> I'm interested in solving this issue @SaranDharshanSP

Hey @priyansh-narang2308 , you've been assigned this issue under Amrita Winter of Code! Please ensure to raise a PR by 28/12/2024, or it will be reassigned to someone else. Best of luck! 🫡

**Comment by priyansh-narang2308** [comment]
Created A pull Request . Do check it out 🫡
