### ISSUE TITLE
Navbar Misalignment on Subpages

### ISSUE THREAD

**Issue by SaranDharshanSP** [SaranDharshanSP/TN-Tourism.github.io#4]
### Description
The navigation bar is not properly aligned on the following subpages: **Food**, **Culture**, **History**, and **Spiritual**. This results in inconsistent UI and affects user navigation.

### Steps to Reproduce
1. Navigate to any of the subpages (Food, Culture, History, or Spiritual).
2. Observe the navbar's alignment compared to the main page.

### Expected Behavior
The navbar should be consistently aligned across all pages, maintaining a uniform look and feel.

### Current Behavior
The navbar appears misaligned or inconsistent in its positioning and styling on the mentioned subpages.

### Severity
**Medium**  
*Impacts the aesthetic and usability of the website.*

### Suggested Fix
- Ensure the same CSS styling is applied to the navbar across all pages.
- Check for inconsistencies in the HTML structure of the navbar in the subpages.
- Test alignment across different screen sizes for responsiveness.

**Comment by rev-sin** [comment]
I'm interested on fixing this issue @SaranDharshanSP

**Comment by SaranHiruthikM** [comment]
Since I've worked more issues like this, would love to solve this one if you assign this to me. @SaranDharshanSP

**Comment by Raamprathap** [comment]
I'm interested in solving this issue @SaranDharshanSP

**Comment by SaranDharshanSP** [comment]
> I'm interested in solving this issue @SaranDharshanSP

Hey! Under Amrita Winter of Code, only one issue can be assigned per person per repository. Please complete your currently assigned issue and raise a PR before requesting another. Looking forward to your contributions!

**Comment by SaranDharshanSP** [comment]
> Since I've worked more issues like this, would love to solve this one if you assign this to me. @SaranDharshanSP

Hey! Noticed that you've already been assigned issues under two other repositories. Please complete those and raise PRs before requesting this issue. Excited to see your contributions!

**Comment by thecodingvivek** [comment]
I am interested to contribute to this issue @SaranDharshanSP  :)

**Comment by SaranDharshanSP** [comment]
> I am interested to contribute to this issue @SaranDharshanSP :)

Hey  @thecodingvivek  , you've been assigned this issue under Amrita Winter of Code! Please ensure to raise a PR by 28/12/2024, or it will be reassigned to someone else. Best of luck! 🫡

**Comment by adithya-menon-r** [comment]
Hey @SaranDharshanSP, I would like to solve this issue if there is no progress.
