### ISSUE TITLE
Home Button in Navbar Returns 404 Error

### ISSUE THREAD

**Issue by SaranDharshanSP** [SaranDharshanSP/TN-Tourism.github.io#5]
### Description
In some subpages, the **Home** button in the navigation bar is not functioning correctly and redirects to a 404 error page.

### Steps to Reproduce
1. Navigate to specific subpages (e.g., Food, Culture, History, or Spiritual).
2. Click on the **Home** button in the navigation bar.
3. Observe that a 404 error is displayed.

### Expected Behavior
The **Home** button should redirect users to the main homepage without any errors.

### Current Behavior
The **Home** button leads to a 404 error on some subpages.

### Severity
**High**  
*This issue affects navigation and disrupts the user experience.*

### Suggested Fix
- Check the `href` or route associated with the **Home** button in the subpages.
- Update the link to correctly point to the homepage route (e.g., `/` or the appropriate path).
- Ensure consistency in the navbar links across all subpages.

**Comment by karthik-saiharsh** [comment]
Interested to work on this @SaranDharshanSP

**Comment by anusanth26** [comment]
I'm interested in working on this issue... I have a pretty good idea to fix the issue @SaranDharshanSP

**Comment by rev-sin** [comment]
Count me in, I'm interested to work on this @SaranDharshanSP

**Comment by Raamprathap** [comment]
I'm interested in solving this issue @SaranDharshanSP

**Comment by SaranDharshanSP** [comment]
> I'm interested in solving this issue @SaranDharshanSP

Hey @Raamprathap ! Under Amrita Winter of Code, only one issue can be assigned per person per repository. Please complete your currently assigned issue and raise a PR before requesting another. Looking forward to your contributions!

**Comment by SaranDharshanSP** [comment]
Hey @karthik-saiharsh @rev-sin @Raamprathap ! AMWOC Started from 10 am today, if you guys still want to do it please ask again.

**Comment by Raamprathap** [comment]
I am interested in the issue @SaranDharshanSP

**Comment by SaranDharshanSP** [comment]
Hey @Raamprathap  ! Under Amrita Winter of Code, only one issue can be assigned per person per repository. Please complete your currently assigned issue and raise a PR before requesting another. Looking forward to your contributions!

> I am interested in the issue @SaranDharshanSP

**Comment by anusanth26** [comment]
I'm interested in working on this issue and resolving it without affecting the actual structure and functionality of the program.
I am eagerly waiting for your approval!!
 @SaranDharshanSP

**Comment by Kavinesh11** [comment]
On me @SaranDharshanSP anna

**Comment by karthik-saiharsh** [comment]
Yep! Interested @SaranDharshanSP

**Comment by SaranDharshanSP** [comment]
> [anusanth26](/anusanth26)

Hey @anusanth26  , you've been assigned this issue under Amrita Winter of Code! Please ensure to raise a PR by 28/12/2024, or it will be reassigned to someone else. Best of luck! 🫡

**Comment by rev-sin** [comment]
yes i am interested

> Hey @karthik-saiharsh @rev-sin @Raamprathap ! AMWOC Started from 10 am today, if you guys still want to do it please ask again.

**Comment by Kavinesh11** [comment]
I am done with the PR @rev-sin , but dont have access to it

**Comment by SaranDharshanSP** [comment]
@anusanth26 is being assigned first in First come First serve basiss.
If he/she fails to do it then you will be given the next pritioty

**Comment by rev-sin** [comment]
> I am done with the PR @rev-sin , but dont have access to it

I'm not the maintainer @Kavinesh11

**Comment by adithya-menon-r** [comment]
Hey @SaranDharshanSP, I would like to solve this issue if there is no progress.
